// $(".localtitle").html("Yilan");
//changeName();
// $("#taipei").mouseenter(function (){
//   $("#taipei ").css("fill","#87a120");
// });
// $("#taipei").mouseleave(function (){
//   $("#taipei ").css("fill","#fff");
// });
$("#taipei").click(function (){
  $(".localtitle1").html("Taipei");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Taipei is Taiwan's largest city as well as its economic, political, and cultural center. It is a modern cosmopolitan metropolis with a lively and diversified face, filled with exuberance.");
  $(".list1").html("Shilin Night Market");
  $(".list2").html("Taipei 101");
  $(".list3").html("Yangmingshan");
  $(".list4").html("Beitou Museum");
  $(".list5").html("Dadaocheng Wharf");
  $("#taipei ").css("fill","#333");
  $("#yilan ").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/taipeibg.jpg');
  $(".smallpic").attr('src','img/tpes.png');
});
$("#newTaipeiCity").click(function (){
  $(".localtitle1").html("New Taipei City");
  $(".localcontent").html("New Taipei City is rich in cultural resources. It's a major cultural county that hosts a rich variety of cultural activities, preserving the memory of the common history and culture.");
  $(".list1").html("Tamsui");
  $(".list2").html("Jiufen");
  $(".list3").html("Yehliu Geopark");
  $(".list4").html("Pingxi");
  $(".list5").html("Buyen Pavilion");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#333333");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/ntp.jpg');
  $(".smallpic").attr('src','img/ntps.png');
});
$("#keelung").click(function (){
  $(".localtitle1").html("Keelung");
  // $(".tinycity").html('<img id="city" src="img/yilan.svg" alt="yilan">');
  $(".localcontent").html("With mountains surrounding on three sides, while The Eastern Sea in its north front, Keelung serves as a natural harbor with immense water, and has its bay cut into downtown deeply.");
  $(".list1").html("Miaokou Snacks");
  $(".list2").html("Bisha Fishing Harbor");
  $(".list3").html("Keelung Harbor");
  $(".list4").html("Wangyou Village");
  $(".list5").html("Badouzi Train Station");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#333333");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/klu.jpg');
  $(".smallpic").attr('src','img/klus-01.png');
});
$("#yilan").click(function (){
  $(".localtitle1").html("Yilan");
  // $(".tinycity").html('<img id="city" src="img/yilan.svg" alt="yilan">');
  $(".localcontent").html("The city of Yilan is located in the central and most favored part of the Lanyang Plain. Streams and rivers provide a constant source of replenishment for the nutrients in the soil here.");
  $(".list1").html("Whale ＆ Dolphin");
  $(".list2").html("Night Market");
  $(".list3").html("Cold and Hot Springs");
  $(".list4").html("Lanyang Museum");
  $(".list5").html("Mingchi Forest");
  $("#yilan ").css("fill","#333333");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/yilanbg.jpg');
  $(".smallpic").attr('src','img/ylas.png');
});
$("#taoyuan").click(function (){
  $(".localtitle1").html("Taoyuan");
  $("#city").attr('src','yl2.png');
  $(".localcontent").html("Taoyuan City is a plateau lies in the northwestern part of Taiwan Main Island. Its cultural diversity earns the nicknames of the 'flower kingdom' and 'land of a thousand ponds.'");
  $(".list1").html("Daxi Old Street");
  $(".list2").html("Shimen Reservoir");
  $(".list3").html("Daxi Tea Factory");
  $(".list4").html("Xiao Wulai Skywalk");
  $(".list5").html("Mesona Flower Festival");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#333333");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/ty.jpg');
  $(".smallpic").attr('src','img/tysh.png');
});
$("#hsinchu").click(function (){
  $(".localtitle1").html("Hsinchu");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Hsinchu County is home to the largest Taiwanese Hakka community. Most of them landed at Hongmao Harbor and Nanliao Harbor, the majority coming from Haifeng and Lufeng in China.");
  $(".list1").html("Hukou Old Street");
  $(".list2").html("Beipu Cold Spring");
  $(".list3").html("Guanwu Park");
  $(".list4").html("Neiwan Township");
  $(".list5").html("Sinfong Township");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#333333");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/hc.jpg');
  $(".smallpic").attr('src','img/hs.png');
});
$("#hsinchuCity").click(function (){
  $(".localtitle1").html("Hsinchu City");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("The town of Hsinchu, now famous for its Science-based Industrial Park, was first developed in 1723. It was first called Hsinchu in 1875, and was upgraded to a provincial city in 1982.");
  $(".list1").html("Siangshan Wetland");
  $(".list2").html("Glass Museum");
  $(".list3").html("Grassland");
  $(".list4").html("Green Grass Lake");
  $(".list5").html("Shibajian Mountain");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#333333");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/hscc.jpg');
  $(".smallpic").attr('src','img/hscc.png');
});
$("#miaoli").click(function (){
  $(".localtitle1").html("Miaoli");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Miaoli is one of the best travel and vacation spots in western Taiwan. Their six major attractions include the tung blossoms, wood sculpture, hot springs, fruit, ceramics, and Hakka food.");
  $(".list1").html("Sanyi Wood Sculpture");
  $(".list2").html("Tai'an Hot Springs");
  $(".list3").html("Longteng Bridge");
  $(".list4").html("Shengxing Train Station");
  $(".list5").html("Huoyan Mountain");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#333333");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/mli.jpg');
  $(".smallpic").attr('src','img/mli.png');
});
$("#taichung").click(function (){
  $(".localtitle1").html("Taichung");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Taiwan's second largest city; Taichung enjoys a mild year-round climate with thriving cultural scenes, friendly people, and beautiful scenery");
  $(".list1").html("Fengjia Night Market");
  $(".list2").html("Wuling Farm");
  $(".list3").html("National Taichung Theater");
  $(".list4").html("Tunghai University");
  $(".list5").html("Shei-Pa National Park");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#333");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/tc.jpg');
  $(".smallpic").attr('src','img/tcs.png');
});
$("#changhua").click(function (){
  $(".localtitle1").html("Changhua");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("The flat and fertile land of Changhua has earned this county a reputation as the breadbasket of Taiwan. Known originally as 'Banxian,' this area was one of the first to be developed in Taiwan.");
  $(".list1").html("Lukang Old Street");
  $(".list2").html("Wanggong Port");
  $(".list3").html("Tianwei Highway");
  $(".list4").html("Jinsheng Lane");
  $(".list5").html("Taiwan Glove Museum");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#333");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/chua.jpg');
  $(".smallpic").attr('src','img/chuas.png');
});
$("#nantou").click(function (){
  $(".localtitle1").html("Nantou");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Nantou County lies at the geographical heart of Taiwan and is the only county that does not border the coast. It is home to Taiwan's highest peak, Yushan and 41 other 3,000-plus-meter mountains.");
  $(".list1").html("Sun Moon Lake");
  $(".list2").html("Hehuanshan");
  $(".list3").html("Qingjing Farm");
  $(".list4").html("Yu Mountain");
  $(".list5").html("Dongpu Hot Springs");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#333");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/nt.jpg');
  $(".smallpic").attr('src','img/ntao.png');
});
$("#yunling").click(function (){
  $(".localtitle1").html("Yunlin");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Yunlin is located in the south-central part of western Taiwan at the northern end of the Jianan Plain. As a county built on agriculture, Yunlin has long taken pride in its rustic charm and high-quality agricultural products.");
  $(".list1").html("Yiwu Detention Pond");
  $(".list2").html("Caoling");
  $(".list3").html("Xiluo Bridge");
  $(".list4").html("Janfusun");
  $(".list5").html("Taiping Old Street");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#333");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/yl.jpg');
  $(".smallpic").attr('src','img/yl.png');
});
$("#chiayi").click(function (){
  $(".localtitle1").html("Chiayi");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("There are three major national scenic areas in Chiayi: Alishan, Southwest Coast, and Siraya National Scenic Area, each presenting a unique view of nature's wonders, from mountains to plains to ocean views.");
  $(".list1").html("Alishan Forest Railway");
  $(".list2").html("Botanical Garden");
  $(".list3").html("City Culture Center");
  $(".list4").html("Municipal Museum");
  $(".list5").html("Historical Relic Museum");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#333");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/cyi.jpg');
  $(".smallpic").attr('src','img/cyi.png');
});

$("#tainan").click(function (){
  $(".localtitle1").html("Tainan");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Tainan is the birthplace of Taiwan and the oldest city on the island. It boasts a stunning natural landscape and well-known agricultural and fishery products and cuisine. ");
  $(".list1").html("Anping Old Fort");
  $(".list2").html("Taijiang Park");
  $(".list3").html("Chi Mei Museum");
  $(".list4").html("Crystal Church");
  $(".list5").html("Jingzaijiao Salt Fields");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#333");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/tnan.jpg');
  $(".smallpic").attr('src','img/tn.png');
});
$("#kaohsiung").click(function (){
  $(".localtitle1").html("Kaohsiung");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Located in the southern part of Taiwan, the city of Kaohsiung is the island's largest industrial center. It also offers port, cultural, and historic attractions with scenic mountains, ocean views, and rivers.");
  $(".list1").html("Love River");
  $(".list2").html("Xizi Bay");
  $(".list3").html("Liuhe Night Market");
  $(".list4").html("Former British Consulate");
  $(".list5").html("Dome of Light");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#333");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/ks.jpg');
  $(".smallpic").attr('src','img/ks.png');
});
$("#pintung").click(function (){
  $(".localtitle1").html("Pingtung");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Taiwan's southernmost county, Pingtung covers a long and narrow territory with a border defined by mountains to the north, the Pacific Ocean to the east, the Taiwan Strait to the west, and the Bashi Channel to the south.");
  $(".list1").html("Kenting National Park");
  $(".list2").html("Aquarium");
  $(".list3").html("Little Liuqiu");
  $(".list4").html("Eluanbi Lighthouse");
  $(".list5").html("Cifong Wetland");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#333");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/pt.jpg');
  $(".smallpic").attr('src','img/pt.png');
});
$("#taitung").click(function (){
  $(".localtitle1").html("Taitung");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("From coastal areas to mountain highs, Taitung greets visitors to a land of ecological richness and scenic beauty. It is also known for its distinctive local products, from premium rice, day lilies, to seafoods.");
  $(".list1").html("Taimali Township");
  $(".list2").html("Brown Boulevard");
  $(".list3").html("Duoliang Station");
  $(".list4").html("Luye Plateau");
  $(".list5").html("Green Island");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#333");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/tt.jpg');
  $(".smallpic").attr('src','img/tt-01.png');
});
$("#hualian").click(function (){
  $(".localtitle1").html("Hualien");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("In 1590, Portuguese sailors passed by the eastern coast of Taiwan and were so astonished that they named this land 'Formosa', the beautiful island. Since then, the majestic views of Hualien have come to represent Taiwan.");
  $(".list1").html("Taroko National Park");
  $(".list2").html("East Rift Valley");
  $(".list3").html("Qingshui Cliff");
  $(".list4").html("Qixing Lake ");
  $(".list5").html("Liushishi Mountain");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#333");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/hual.jpg');
  $(".smallpic").attr('src','img/hual.png');
});
$("#penghu").click(function (){
  $(".localtitle1").html("Penghu");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Penghu is known as the pearl of the Taiwan Strait. Composed of 90 islands, the county is blessed with magnificent ocean views and many other natural wonders.");
  $(".list1").html("Penghu Great Bridge ");
  $(".list2").html("Twin Heart Stone Weir");
  $(".list3").html("Xianjiao Island");
  $(".list4").html("Tongpan Park");
  $(".list5").html("Xiaomen Islet");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#333");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/phu.jpg');
  $(".smallpic").attr('src','img/phu.png');
});
$("#kingman").click(function (){
  $(".localtitle1").html("Kinmen");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Kinmen, also known as Quemoy, is a small island with a very big reputation. Situated just off the coast of Mainland China, it was the site of fierce fighting between Communist and Nationalist forces.");
  $(".list1").html("Kinmen Cihu");
  $(".list2").html("Juguang Tower");
  $(".list3").html("Mashan Station");
  $(".list4").html("Zhaishan Tunnel");
  $(".list5").html("Jincheng Township");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#333");
  $(".mazhu").css("fill","#fff");
  $(".localpic").attr('src','img/km.jpg');
  $(".smallpic").attr('src','img/km.png');
});
$("#mazhu").click(function (){
  $(".localtitle1").html("Matzu");
  // $("#city").attr('src','yl2.png');
  $(".localcontent").html("Named after the goddess Mazu, the Matsu Islands are composed of dozens of islands. The chain occupies the northernmost edge of the west-northwest side of the Taiwan Strait");
  $(".list1").html("Qinbi Village");
  $(".list2").html("Bi Mountain");
  $(".list3").html("Beihai Tunnel");
  $(".list4").html("Dongyong Lighthouse");
  $(".list5").html("Matzu National Scenic Area");
  $("#yilan ").css("fill","#fff");
  $("#taipei").css("fill","#fff");
  $("#taoyuan").css("fill","#fff");
  $("#newTaipeiCity").css("fill","#fff");
  $("#keelung").css("fill","#fff");
  $("#hsinchu").css("fill","#fff");
  $("#hsinchuCity").css("fill","#fff");
  $("#miaoli").css("fill","#fff");
  $("#taichung").css("fill","#fff");
  $("#changhua").css("fill","#fff");
  $("#nantou").css("fill","#fff");
  $("#yunling").css("fill","#fff");
  $("#chiayi").css("fill","#fff");
  $("#tainan").css("fill","#fff");
  $("#kaohsiung").css("fill","#fff");
  $("#pintung").css("fill","#fff");
  $("#taitung").css("fill","#fff");
  $("#hualian").css("fill","#fff");
  $(".penghu").css("fill","#fff");
  $(".kingman").css("fill","#fff");
  $(".mazhu").css("fill","#333");
  $(".localpic").attr('src','img/mz.jpg');
  $(".smallpic").attr('src','img/mz.png');
});